README.mdown

It is either 'a couple of' or 'a few'.

Superfluous word in Readme.

---

Mollie/API/Client.py
Mollie/API/Error.py
Mollie/API/Object/Customer.py
Mollie/API/Object/Mandate.py
Mollie/API/Object/Payment.py
Mollie/API/Object/Subscription.py
Mollie/API/Object/__init__.py
Mollie/API/Resource/Base.py
Mollie/API/Resource/CustomerPayments.py
Mollie/API/Resource/Customers.py
Mollie/API/Resource/Mandates.py
Mollie/API/Resource/Payments.py
Mollie/API/Resource/Subscriptions.py
Mollie/API/Resource/__init__.py

I need to use the recurring interface and I don't know when you guys will release the next version, so I whipped something up myself.

 Updated API for recurring interface (Customer, Mandate, Subscription) 

---

mollie/api/objects/issuer.py
mollie/api/objects/method.py
tests/responses/method_get_ideal.json
tests/responses/method_get_ideal_with_includes.json
tests/test_issuers.py
tests/test_methods.py

As discussed in: https://github.com/mollie/mollie-api-python/pull/45#discussion_r208895970
Merge #46 first please

Implement SVG image

---

mollie/api/objects/issuer.py
mollie/api/objects/method.py
mollie/api/objects/payment.py
tests/responses/method_get_ideal.json
tests/responses/method_get_ideal_with_includes.json
tests/responses/payment_single.json
tests/test_issuers.py
tests/test_methods.py
tests/test_payments.py

Addresses https://github.com/mollie/mollie-api-python/pull/45#discussion_r208906003
The Settlement API is not yet implemented (planned for a future sprint), so we don't have wrapper objects for that yet. Implemented this partially.
Merge #47 first please.

Payment link handling

---

mollie/api/objects/payment.py
setup.cfg
tests/responses/payment_single.json
tests/test_payments.py

As discussed in https://github.com/mollie/mollie-api-python/pull/45#discussion_r208908259
- added missing properties
- reordered all properties to be in sync with the docs, same for tests

Payment properties

---

mollie/api/objects/refund.py
tests/test_payment_refunds.py

As discussed in https://github.com/mollie/mollie-api-python/pull/45#discussion_r208908891
Merge #49 first, please

Refund properties

---

mollie/api/client.py
mollie/api/objects/base.py
mollie/api/objects/issuer.py
mollie/api/resources/customer_mandates.py
mollie/api/resources/customer_subscriptions.py
mollie/api/resources/customers.py
mollie/api/resources/payments.py
mollie/api/resources/refunds.py
setup.cfg
tests/responses/error_teapot.json
tests/test_client.py
tests/test_customer_payments.py
tests/test_customer_subscriptions.py
tests/test_payments.py

Addressing https://github.com/mollie/mollie-api-python/pull/45#discussion_r208597244
- refactored `_resource` assignment
- Added some additional tests to improve coverage
Merge #50 first please

Refactor resource

---

examples/1-new-payment.py
examples/10-customer-payment-history.py
examples/11-refund-payment.py
examples/2-webhook-verification.py
examples/3-return-page.py
examples/4-ideal-payment.py
examples/5-payments-history.py
examples/6-list-activated-methods.py
examples/7-new-customer.py
examples/8-list-customers.py
examples/9-create-customer-payment.py
examples/app.py
mollie/api/client.py
mollie/api/objects/list.py
mollie/api/resources/base.py
mollie/api/resources/chargebacks.py
mollie/api/resources/customer_mandates.py
mollie/api/resources/customer_payments.py
mollie/api/resources/customer_subscriptions.py
mollie/api/resources/customers.py
mollie/api/resources/payment_chargebacks.py
mollie/api/resources/payment_refunds.py
mollie/api/resources/payments.py
mollie/api/resources/refunds.py
tests/test_client.py

Addresses https://github.com/mollie/mollie-api-python/pull/45#discussion_r208542381
Merge #52 first please.

Use str.format()

---

mollie/api/objects/payment.py
tests/test_payments.py

Add new authorized status and authorized_at property

---

mollie/api/client.py
tests/test_client.py

Add possibility to define timeout on client

---

tests/test_customer_mandates.py

Add test for revoking a customer mandate

---

mollie/api/client.py
tests/test_client.py

Should resolve #99 , as far as setting a valid access token for communication with the API.

Oauth access tokens

---

mollie/api/client.py
tests/test_client.py

User agent components

---

Makefile
README.md
mollie/api/client.py
tests/conftest.py
tests/responses/token_single.json
tests/test_client.py
tests/test_invoices.py
tests/test_onboarding.py
tests/test_organizations.py
tests/test_permissions.py
tests/test_profiles.py
tests/test_requests_oauthlib.py
tests/test_settlement_captures.py
tests/test_settlement_chargebacks.py
tests/test_settlement_payments.py
tests/test_settlement_refunds.py
tests/test_settlements.py

Some changes to the oauth code, and some cleanup (unrelated to oauth)

Oauth additions

---

mollie/api/objects/method.py
tests/responses/method_get_ideal.json
tests/responses/method_get_ideal_with_includes.json
tests/responses/method_get_ideal_wrong_images.json
tests/responses/methods_list.json
tests/test_methods.py

https://github.com/mollie/mollie-api-python/issues/105

105 methods min max

---

mollie/api/objects/refund.py
tests/responses/refund_single.json
tests/test_orders.py
tests/test_payment_refunds.py

Fix for https://github.com/mollie/mollie-api-python/issues/136

Add metadata propery for refunds, expand tests

---

mollie/api/objects/method.py
tests/responses/method_get_ideal.json
tests/test_methods.py

Add support for method pricing.

---

Makefile
setup.cfg
test_requirements.txt

Improve testing routine by setting some versions for packages we require for testing.

Fix travis on master

---

examples/01-new-payment.py
examples/04-ideal-payment.py
examples/09-create-customer-payment.py

Fix typo in script name in examples, reported by @surfchrisman.

---

mollie/api/objects/method.py

Resolves https://github.com/mollie/mollie-api-python/issues/163

Add support for payment method mealvoucher

---

mollie/api/objects/organization.py
tests/responses/organization_current.json
tests/test_organizations.py

Resolves https://github.com/mollie/mollie-api-python/issues/161

Add dashboard url property to organization

---

tests/responses/settlement_single.json
tests/test_settlements.py

Resolves https://github.com/mollie/mollie-api-python/issues/162

Add invoiceId for each monthly period in Settlements test response

---

mollie/api/resources/settlement_payments.py
mollie/api/resources/settlement_refunds.py
tests/test_settlement_payments.py
tests/test_settlement_refunds.py
tests/test_settlements.py

Those endpoints are working for me locally.
I changed the tests accordingly.

fix the payments + refunds settlements endpoints

---

mollie/api/objects/order_line.py
mollie/api/objects/subscription.py
tests/responses/order_single.json
tests/responses/subscription_single.json
tests/test_customer_subscriptions.py
tests/test_order_lines.py

Add the metadata property to CustomerSubscription and OrderLine objects.

---

.gitignore
.travis.yml
Makefile

And some other upgrades to the (test) setup

Switch to py38 as default

---

.travis.yml
README.md

See https://www.python.org/downloads/release/python-3510/

Remove python 3.5 from tests, python3.5 is EOL.

---

tests/test_order_lines.py

https://docs.mollie.com/changelog/v2/changelog#april-2021

Add sku to the payload when updating orderline data

---

MANIFEST.in

Put less stuff in the final distributed package.

Cleanup package

---

mollie/api/objects/list.py
tests/test_list.py

support sequence behaviour for lists

---

mollie/api/objects/payment.py
tests/responses/payment_single.json
tests/test_payments.py

Based on https://docs.mollie.com/connect/splitting-payments

Add split payment support

---

examples/17-order-return-page.py

Fix typo in example.

---

.github/workflows/test_and_deploy.yaml
Makefile
pyproject.toml
test_requirements.txt

Some generic updates to the test and build setup.

Update test properties

---

.github/workflows/test_and_deploy.yaml
Makefile
pyproject.toml

Support newer python versions.

Test with new pythons

---

v3-api-changes.md

This relates to PR https://github.com/mollie/mollie-api-python/pull/266/

Document all the v2 properties that have been transformed to methods

---

mollie/api/client.py
mollie/api/objects/base.py
mollie/api/objects/capture.py
mollie/api/objects/chargeback.py
mollie/api/resources/base.py
mollie/api/resources/captures.py
mollie/api/resources/chargebacks.py
mollie/api/resources/clients.py
mollie/api/resources/customers.py
mollie/api/resources/invoices.py
mollie/api/resources/mandates.py
mollie/api/resources/methods.py
mollie/api/resources/onboarding.py
mollie/api/resources/order_lines.py
mollie/api/resources/orders.py
mollie/api/resources/organizations.py
mollie/api/resources/payment_links.py
mollie/api/resources/payments.py
mollie/api/resources/permissions.py
mollie/api/resources/profiles.py
mollie/api/resources/refunds.py
mollie/api/resources/settlements.py
mollie/api/resources/shipments.py
mollie/api/resources/subscriptions.py
mypy.ini
pyproject.toml
tests/test_api_client.py

Completed type annotations for all resources code, an added annotations to the main Client as well. We can opt to squash all annotations in resources into one big commit.
Some subtle changes were made to the Client, which were uncovered by the use of type annotations.

More type annotations

---

README.md
mollie/api/version.py
release_process.md

If no other things come up, we can do the final 3.0.0 release later this week.

Release 3.0.0rc3

---

mollie/api/client.py
tests/test_api_client.py

Based on a discussion on Discord with Jonas

When using a dashboard access token, don't add OAuth to the User-Agent

---

mollie/api/objects/order.py
mollie/api/objects/payment.py
tests/responses/order_canceled.json
tests/responses/order_single.json
tests/responses/order_single_with_embeds.json
tests/responses/orders_list.json
tests/responses/payment_canceled.json
tests/responses/payment_link_single.json
tests/responses/payment_links_list.json
tests/responses/payment_single.json
tests/responses/payment_single_no_links.json
tests/responses/payment_updated.json
tests/responses/payments_list.json
tests/test_orders.py
tests/test_payments.py

Add cancelUrl property to Order and Payment objects

---

mollie/api/objects/order.py
mollie/api/objects/payment.py
mollie/api/objects/profile.py
mollie/api/objects/settlement.py

Resolve circular import error when importing the Payment class

---

mollie/api/client.py
mollie/api/error.py
mollie/api/resources/base.py
mollie/api/resources/customers.py
mollie/api/resources/mandates.py
mollie/api/resources/orders.py
mollie/api/resources/payments.py
mollie/api/resources/profiles.py
mollie/api/resources/refunds.py
mollie/api/resources/shipments.py
mollie/api/resources/subscriptions.py
tests/responses/bad_request.json
tests/responses/conflict_error.json
tests/test_api_client.py
tests/test_resource_base.py

Closes https://github.com/mollie/mollie-api-python/issues/299

Add Idempotency-Key header

---

mollie/api/resources/settlements.py

Simplify code that validates Settlement ID

---

mollie/api/objects/order.py
mollie/api/objects/order_line.py
mollie/api/objects/payment.py
mollie/api/objects/payment_link.py
mollie/api/objects/profile.py
mollie/api/objects/settlement.py
tests/test_payments.py

Add Payment.has_settlement() utility method

---

mollie/api/client.py
mollie/api/objects/balance.py
mollie/api/objects/balance_report.py
mollie/api/objects/balance_transaction.py
mollie/api/resources/__init__.py
mollie/api/resources/balances.py
tests/responses/balance_report_single.json
tests/responses/balance_single.json
tests/responses/balance_transactions_list.json
tests/responses/balances_list.json
tests/test_balances.py

Add balances API

---

mollie/api/error.py
tests/test_errors.py

Unrelated changes: updated black formatting in subclasses
Related to: https://github.com/mollie/mollie-api-python/issues/306

Add support for pickling ResponseError exceptions

---

mollie/api/objects/payment.py
mollie/api/resources/captures.py
tests/responses/payment_single.json
tests/responses/payment_single_no_links.json
tests/test_payment_captures.py
tests/test_payments.py

Resolves #309 
~This branch is ready to be merged, we're waiting on the Mollie API to publish the changes required for this to work.~ The manual Capture functionality is currently in closed beta.

Add support for capture on card payments

---

examples/01-new-payment-using-qrcode.py

NTR: Fix create payment qr code example

---

mollie/api/client.py
mollie/api/error.py
mollie/api/objects/client_link.py
mollie/api/resources/__init__.py
mollie/api/resources/client_links.py
tests/responses/client_link_created.json
tests/test_client_links.py

https://docs.mollie.com/reference/create-client-link
Closes: https://github.com/mollie/mollie-api-python/issues/320
I've added:
✅ Add ClientLink object
✅ Add ClientLink resource
✅ Check if Oauth client before attempting to use the ClientLink API
✅ Tests

Add client link

---

MANIFEST.in
setup.py

Supersedes https://github.com/mollie/mollie-api-python/pull/347
Ship only the mollie package. Do not ship tests.
I like `include=["mollie", "mollie.*"]` better then `exclude`.
On master branch `python setup.py build` outputs:
```
running build
running build_py
creating build/lib/tests
copying tests/test_api_client.py -> build/lib/tests
copying tests/test_settlement_payments.py -> build/lib/tests
copying tests/test_payment_links.py -> build/lib/tests
copying tests/conftest.py -> build/lib/tests
copying tests/test_list.py -> build/lib/tests
copying tests/test_methods.py -> build/lib/tests
copying tests/test_customer_mandates.py -> build/lib/tests
copying tests/test_resource_base.py -> build/lib/tests
copying tests/test_profile_refunds.py -> build/lib/tests
copying tests/test_issuers.py -> …
```

Include mollie and nothing else

---

mollie/api/client.py
tests/test_api_client.py

Reverts mollie/mollie-api-python#355
The issue related to the PR is also reopened https://github.com/mollie/mollie-api-python/issues/342.

Revert "Make sure testmode is added to the body on all http_methods except GET"

---

mollie/api/client.py
tests/test_api_client.py

Add testmode to data or params based on HTTP method

---

mollie/api/client.py
tests/test_api_client.py

Fixes https://github.com/mollie/mollie-api-python/issues/342#issuecomment-2368539123

Pass True instead of 'true' for testmode when posting using oauth_client

---

mollie/api/objects/client_link.py
mollie/api/objects/payment.py
tests/responses/payment_single_no_links.json
tests/test_payments.py

373 payment resource updates
