mollie/mollie-api-python

- setup.py
I've added requests as required install/dependency. Maybe there is a reason why requests was not added as dependency in the first place? A reason could be to not interfere with the requests version used in the same project as the one where the Mollie client is being/going to be used.
If no reason for this, I'd like this pull request to be merged into master.
> Added dependency

- .travis.yml
- Mollie/API/Client.py
- Mollie/API/Resource/Base.py
- Mollie/API/__init__.py
- README.md
- setup.py
As noted in #38, it is not clear how, and even worse, not possible to provide query string parameters in requests methods that accept request body parameters (POST requests).
Previously I had implemented that request body parameters could be passed by both a dictionary and keyword arguments. But now it is clear that I had overlooked that POST requests could also have query parameters. So, I have reverted those changes and added that query string parameters can be added to POST request methods as keyword arguments.
To make it totally clear, the following is now default behavior throughout the client:
- For requests that accept request body parameters (POST requests), the `data` parameter can be used to supply a dictionary of request body parameters to the method. In a lot of those methods, …
> Add support for query string parameters for POST requests

- mollie/api/objects/base.py
- mollie/api/objects/customer.py
- mollie/api/objects/mandate.py
- mollie/api/objects/method.py
- mollie/api/objects/payment.py
- mollie/api/objects/subscription.py
- tests/responses/payment_single.json
- tests/test_chargebacks.py
- tests/test_customer_mandates.py
- tests/test_customer_payments.py
- tests/test_customer_subscriptions.py
- tests/test_customers.py
- tests/test_issuers.py
- tests/test_methods.py
- tests/test_payment_chargebacks.py
- tests/test_payment_refunds.py
- tests/test_payments.py
- tests/test_refunds.py
As discussed in: https://github.com/mollie/mollie-api-python/pull/45#discussion_r208892711
- Added `Base._get_link()` method
- Refactored all code to use that in stead of try/except everywhere.
- Fixed and extended a few related tests.
- Some minor docstring fixes.
> Implement Base._get_link() and use it

- examples/10-customer-payment-history.py
- examples/11-refund-payment.py
- examples/5-payments-history.py
- examples/6-list-activated-methods.py
- examples/8-list-customers.py
- examples/9-create-customer-payment.py
- mollie/api/objects/list.py
- mollie/api/resources/base.py
- tests/responses/method_get_ideal_with_includes.json
- tests/test_chargebacks.py
- tests/test_client.py
- tests/test_customer_mandates.py
- tests/test_customer_payments.py
- tests/test_customer_subscriptions.py
- tests/test_customers.py
- tests/test_issuers.py
- tests/test_list.py
- tests/test_methods.py
- tests/test_payment_chargebacks.py
- tests/test_payment_refunds.py
- tests/test_payments.py
- tests/test_refunds.py
- tests/utils.py
Addressing https://github.com/mollie/mollie-api-python/pull/45#discussion_r208945541
- Renamed `.all()` to `.list()`
- Updated all tests
- Removed lots of code duplication in tests to determine correct behaviour of returned lists
- Fixed small bug in list handling that surfaced when iterating over a list twice.
Merge #51 first please
> Rename all to list

- mollie/api/error.py
- mollie/api/resources/base.py
- tests/conftest.py
- tests/responses/order_error.json
- tests/test_client.py
Working around the fact that Mollie sends UTF-8 responses, but doesn't set the HTTP Content-type headers to reflect this (which results in UnicodeDecodeErrors further down the line)
> Unicode responses

- README.md
- mollie/api/client.py
- mollie/api/version.py
- setup.py
A fix for #78 
I tested installing this using:
- `pip install <path to sdist tar.gz>`
- `pip install -e <path to github repo>`
- `pip install -e <path to local checkout>`
In all versions, pip understands which version was installed.
> Setup version in one location

- Makefile
At the moment the travis-ci build fails because of numpy:
> 36810: numpy <=1.16.0 resolved (1.16.0 installed)!
> An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call.
We aren't using numpy, so ignoring this will solve the build failure.
> The automatic installation of numpy by travis-ci causes a security error. Ignore this

- mollie/api/objects/base.py
- mollie/api/objects/customer.py
- mollie/api/objects/list.py
- mollie/api/objects/mandate.py
- mollie/api/objects/order.py
- mollie/api/objects/payment.py
- mollie/api/objects/refund.py
- mollie/api/objects/shipment.py
- mollie/api/objects/subscription.py
- mollie/api/resources/base.py
- mollie/api/resources/customer_mandates.py
- mollie/api/resources/customer_subscriptions.py
- mollie/api/resources/customers.py
- mollie/api/resources/order_lines.py
- mollie/api/resources/orders.py
- mollie/api/resources/payments.py
- mollie/api/resources/refunds.py
- mollie/api/resources/shipments.py
- tests/test_customers.py
- tests/test_payment_refunds.py
- tests/test_payments.py
Remove use of the `object._resource` attribute for retrieving data for related object data. Refactored everything to use the more generic `object.client` attribute.
> Refactor use client not _resource

- mollie/api/client.py
- mollie/api/objects/subscription.py
- mollie/api/resources/subscription_payments.py
- tests/test_customer_subscriptions.py
Solves issue #89 Add support for listing subscription payments
Because the `customer id` is no property of a subscription, and the subscription payments url is not in the subscription response under `_links`, we retrieve the `customer id` in the `SubscriptionPayments` resource through the `customer` object.
> Add support for listing subscription payments

- mollie/api/objects/order.py
- mollie/api/resources/order_payments.py
- tests/responses/payment_single.json
- tests/test_orders.py
- tests/test_payments.py
Regarding issue [#88](https://docs.mollie.com/reference/v2/orders-api/create-order-payment): added a new resource called `OrderPayment` used for creating a new payment for an _existing_ order. Added a method to the order object called `create_payment` used to create the payment, also added a unit test for this method.
> Create order payment

- mollie/api/error.py
- mollie/api/objects/order.py
- mollie/api/resources/order_lines.py
- tests/responses/order_single.json
- tests/test_client.py
- tests/test_order_lines.py
- tests/test_orders.py
Solves issue #87 Add support for updating an orderline
Also create an `DataConsistencyError`, which will be raised when unexpected data is received from the API.
> Add update orderline function to the order object

- tests/responses/payment_updated.json
- tests/test_payments.py
The update payment endpoint was already supported. This test proves it.
Solves #140
> Add test for update payment API endpoint

- mollie/api/client.py
- mollie/api/resources/subscriptions.py
- tests/responses/subscriptions_customer_list.json
- tests/test_customer_subscriptions.py
- tests/test_customers.py
- tests/test_subscriptions.py
A Subscription resource is added, and all the methods except `list()` will raise a `NotImplementedError`. 
Solves #141
> Support new API endpoint: list all subscriptions

- mollie/api/client.py
- tests/test_client.py
Some improvements to the exception handling during requests.
> Requests error handling

- examples/05-payments-history.py
The code displays twice the currency
EUR **EUR**, status: 'paid'
correct display after the commit
EUR **120.00**, status: 'paid'
> fix: currency is displayed twice, display value instead

- mollie/api/error.py
- mollie/api/objects/settlement.py
- tests/test_settlements.py
See deprecation warning for `invoiceId` at https://docs.mollie.com/reference/v2/settlements-api/get-settlement
> Add warning about deprecated feature in Settlements API.

- mollie/api/error.py
This change should have been done before the 2.4.0 release, but was missed.
No harm done: there was nothing to deprecate.
> Update versioning scheme in deprecation warnings.

- mollie/api/client.py
- setup.cfg
- test_requirements.txt
- tests/conftest.py
- tests/test_client.py
Solution for #178 
I opted for configuring the builtin retry mechanism of `urllib3` in stead of building our own version. This might not be as flexible as the PHP version, but it should function just as well, and of course the code is better tested than any custom-built feature.
> Retry failed requests

- mollie/api/resources/subscription_payments.py
- tests/test_customer_subscriptions.py
See the docs: https://docs.mollie.com/reference/v2/subscriptions-api/list-subscriptions-payments
This should fix issue #190.
> Fix invalid get subscription payments endpoint url

- mollie/api/client.py
This makes the timeout behaviour identical to the PHP client.
Also added a docstring describing the parameters.
> Change default timeouts for the API client.

- mollie/api/client.py
Mollie wants to use a retry policy that is enabled by default.
Based on a discussion on Slack with @rares-mollie
> Set default number of retry attempts to three.

- mollie/api/client.py
- tests/conftest.py
- tests/test_customer_mandates.py
- tests/test_customer_payments.py
- tests/test_customer_subscriptions.py
- tests/test_customers.py
- tests/test_invoices.py
- tests/test_onboarding.py
- tests/test_organizations.py
- tests/test_payment_captures.py
- tests/test_payment_chargebacks.py
- tests/test_payment_refunds.py
- tests/test_payments.py
- tests/test_permissions.py
- tests/test_profile_chargebacks.py
- tests/test_profile_methods.py
- tests/test_profile_payments.py
- tests/test_profile_refunds.py
- tests/test_profiles.py
- tests/test_settlement_captures.py
- tests/test_settlement_chargebacks.py
- tests/test_settlement_payments.py
- tests/test_settlement_refunds.py
- tests/test_settlements.py
Remove deprecated string interpolation syntax. Since we now support python 3.6 and up, replace everything with f-strings.
> Remove string interpolation using percentage sign.

- mollie/api/error.py
- mollie/api/objects/order.py
- mollie/api/resources/base.py
- mollie/api/resources/orders.py
- tests/responses/order_single_with_embeds.json
- tests/test_orders.py
- tests/utils.py
There is no easy way to access the payments related to an order, other than using the embedded data. We have no support for accessing embedded data up to now. 
This PR helps a customer that wants to access all payments related to an order, and serves as a proposal on how to access embedded data. In the future, we can apply this method to other embedded datasets as well, thereby giving access to more data  and lowering API calls.
> Allow easy access to order payments through the order object.

- mollie/api/objects/payment.py
- tests/responses/payment_single_no_links.json
- tests/test_payments.py
If the payment contains no links to related objects, then omit the API call before returning an empty Object or ObjectList.
> Omit useless API calls for data related to payments.

- mollie/api/client.py
- test_requirements.txt
- tests/test_client.py
- tests/test_orders.py
See https://github.com/getsentry/responses#deprecations-and-migration-path:
``Deprecated Functionality: match_querystring argument in Response and CallbackResponse``.
> Fix responses deprecation warning

- .github/workflows/test_and_deploy.yaml
- README.md
- pyproject.toml
It should still work but we don't test or support it actively anymore.
> Remove references to deprecated Python 3.6.

- mollie/api/resources/base.py
- mollie/api/resources/captures.py
- mollie/api/resources/chargebacks.py
- mollie/api/resources/clients.py
- mollie/api/resources/customer_mandates.py
- mollie/api/resources/customer_subscriptions.py
- mollie/api/resources/customers.py
- mollie/api/resources/invoices.py
- mollie/api/resources/methods.py
- mollie/api/resources/onboarding.py
- mollie/api/resources/order_lines.py
- mollie/api/resources/orders.py
- mollie/api/resources/organizations.py
- mollie/api/resources/payment_links.py
- mollie/api/resources/payments.py
- mollie/api/resources/permissions.py
- mollie/api/resources/profile_methods.py
- mollie/api/resources/profiles.py
- mollie/api/resources/refunds.py
- mollie/api/resources/settlements.py
- mollie/api/resources/shipments.py
- mollie/api/resources/subscriptions.py
- tests/test_payment_captures.py
- tests/test_payment_chargebacks.py
- tests/test_settlement_captures.py
- tests/test_subscriptions.py
Currently, all resources in the client have all API manipulation methods (`.list()`, `.get()`, `.create()`, `.delete()`, `.update()`), but many resources only support a subset of these (f.i. [chargebacks are read-only](https://docs.mollie.com/reference/v2/chargebacks-api/overview) but the client has a `.create()` for chargebacks that always will result in an error.
This PR corrects this, and removes resource methods from resources that aren't supported, leaving only the supported methods in place.
Related to #255
> Remove unused resource methods.

- README.md
There is already a link to https://jobs.mollie.com, so no need for a replacement URL I think.
Related to #267
> Remove broken link to the no longer existing Mollie blog.

- .github/workflows/release.yaml
- release_process.md
From now on, we should use the Python versioning scheme to tag releases, e.g. no longer use `v3.0.0` but just `3.0.0`.
I'll tag all 3.x releases in retrospect with these versions.
> Update docs and release scheme to use the python versioning scheme.

- mollie/api/resources/base.py
- mollie/api/resources/captures.py
- mollie/api/resources/chargebacks.py
- mollie/api/resources/clients.py
- mollie/api/resources/customers.py
- mollie/api/resources/invoices.py
- mollie/api/resources/mandates.py
- mollie/api/resources/methods.py
- mollie/api/resources/onboarding.py
- mollie/api/resources/order_lines.py
- mollie/api/resources/orders.py
- mollie/api/resources/organizations.py
- mollie/api/resources/payment_links.py
- mollie/api/resources/payments.py
- mollie/api/resources/permissions.py
- mollie/api/resources/profiles.py
- mollie/api/resources/refunds.py
- mollie/api/resources/settlements.py
- mollie/api/resources/shipments.py
- mollie/api/resources/subscriptions.py
`**kwargs` should be annotated using only the type of the `value` in a `keyword=value` keyword argument.
Typing this as f.i. `**kwargs: str` means that all provided argument values need to be strings, which we can't support: `.list(limit=47)` uses an int, and it is valid usage. This leaves us with `Any` for now.
> Remove incorrect type annotation from **kwargs

- mollie/api/resources/methods.py
The static list of payment methods that should be controlled by enabling/disabling issuers doesn't need to wrapped by a method, so removing this oversight.
> Use class constant for returning a static list, no property method

- mollie/api/objects/payment.py
- tests/test_payments.py
This was falsely removed during the refactor for 3.0.0
https://github.com/mollie/mollie-api-python/issues/292
> Add back the `Payment.subscription_id` property

- .github/workflows/tests.yaml
- mollie/api/client.py
- pyproject.toml
- tests/conftest.py
- tests/test_api_client.py
- tests/test_payment_refunds.py
Resolves #273 
Note: when overriding an enabled `testmode` for a single call (see the `test_override_testmode` test), we're sending `testmode=false` in stead of leaving the parameter out. I tested this (using [mollie-cli](https://pypi.org/project/mollie-cli/)) on a few endpoints, and it was accepted on all of them.
> Enable testmode globally

- .github/workflows/tests.yaml
- mollie/api/version.py
- mollie/py.typed
- setup.py
- test_requirements.txt
We need this to actually make use of the declared types when type-checking downstream packages.
> Add type annotations marker

- mollie/api/resources/onboarding.py
- tests/test_onboarding.py
Mollie has decided to move a different mechanism for onboarding, this endpoint will continue to work but is deprecated.
As per the [changelog](https://docs.mollie.com/changelog/v2/changelog#may-2023) and the [endpoint docs](https://docs.mollie.com/reference/v2/onboarding-api/submit-onboarding-data)
> Deprecate the 'Submit onboarding data' endpoint

- mollie/api/objects/balance_report.py
- mollie/api/objects/balance_transaction.py
- mollie/api/objects/base.py
- mollie/api/objects/capture.py
- mollie/api/objects/mandate.py
- mollie/api/objects/order_line.py
- mollie/api/objects/payment.py
- mollie/api/objects/subscription.py
- mypy.ini
This uncovers various issues with the implementation of `get_resource_class()`. Now we have mypy passing and the code should work in theory, but the only place where this method is used (in `ObjectList`), already shows clearly that the current approach won't work.
We need to rethink the way ObjectList works, and hopefully get rid of `get_resource_class()` entirely.
For now: the code stays the same, but with working type annotations.
> Enable mypy 'check_untyped_defs'

- mollie/api/client.py
Only connect errors should be retried according to specification.
Ref: #325
> A read timeout error should not be retried

- mollie/api/objects/chargeback.py
- mollie/api/objects/subscription.py
- mollie/api/resources/base.py
- tests/test_customer_subscriptions.py
- tests/test_payment_chargebacks.py
There has been mention of API identifiers that contain a `.` (dot) character, see https://github.com/mollie/magento2/issues/669
Just to be sure, we refactor these regular expressions so that we won't run into the same issue in the future. We are now allowing any character in the identifier, we handle termination using either the end of the regex, or a slash which would indicate a new subpart of the URL.
> Refactor regular expressions that extract identifiers from URLs

- .github/workflows/tests.yaml
Note: Flake8/pycodestyle has several issues with Python3.12, all related to the fact that in Python3.12, f-strings can be tokenized. We just need to wait for another release.
> Test with Python 3.12

- .github/workflows/tests.yaml
- mollie/api/resources/balances.py
- mollie/api/resources/settlements.py
- tests/test_settlements.py
Mollie merchant IDs are now longer.
Related to #335
> Allow a longer bank reference

- mollie/api/objects/balance.py
- tests/test_balances.py
This fixes the problems with the params being incorrectly passed to the get_transactions method on the Balance class.
> Unpack params before performing calling get_transactions and get_report

- mollie/api/client.py
The OAuth Authroize URL has changed from www.mollie.com to my.mollie.com. This change is to reflect that.
> IMP-610: Use correct OAuth Authorize URL

- .github/workflows/release.yaml
Recently, dependabot upgraded download-artifact to v4 https://github.com/mollie/mollie-api-python/pull/365.
This is causing issues when publishing the package to pypi, because this download-artifact version is incompatible with upload-artifact v3. (https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md#which-versions-of-the-artifacts-packages-are-compatible)
This PR upgrades upload-artifact to v4, as well as the checkout action.
> Use upload-artifact v4 since v3 is not compatible with download-artifact v4
